import type { GameTuning, VisualTheme, WeaponConfig } from "./types";

export const visualTheme: VisualTheme = {
  skyTop: "#3f6a8f",
  skyHorizon: "#dbae7d",
  sun: "#ffd89a",
  mud: "#3f3226",
  foliage: "#2c7448",
  foliageDark: "#0e2a22",
  metal: "#27323a",
  warning: "#d89445",
  hudPrimary: "#d7dde1",
  hudDanger: "#ff2f2f",
  fogDensity: 0.013,
  lightIntensity: 1.12,
  vegetationDensity: 1.12,
  tracerIntensity: 1.35,
};

export const weapons: Record<"carbine" | "marksman" | "shotgun", WeaponConfig> = {
  carbine: {
    id: "carbine",
    label: "Trail Carbine",
    shortLabel: "CARBINE",
    magazineSize: 24,
    damage: 34,
    critMultiplier: 2.1,
    fireIntervalSeconds: 0.14,
    reloadSeconds: 1.25,
    range: 66,
    recoil: 0.018,
    spread: 0.014,
  },
  marksman: {
    id: "marksman",
    label: "Riverline Marksman",
    shortLabel: "MARKSMAN",
    magazineSize: 8,
    damage: 78,
    critMultiplier: 2.65,
    fireIntervalSeconds: 0.5,
    reloadSeconds: 1.65,
    range: 96,
    recoil: 0.034,
    spread: 0.006,
  },
  shotgun: {
    id: "shotgun",
    label: "Gate 12G",
    shortLabel: "SHOTGUN",
    magazineSize: 6,
    damage: 104,
    critMultiplier: 1.65,
    fireIntervalSeconds: 0.78,
    reloadSeconds: 1.9,
    range: 40,
    recoil: 0.056,
    spread: 0.05,
  },
};

export const tuning: GameTuning = {
  missionSeconds: 110,
  baseIntegrity: 100,
  attackLineZ: -6.5,
  enemySpawnZ: 30,
  lanes: {
    left: -8,
    center: 0,
    right: 8,
  },
  weapon: weapons.marksman,
  defaultWeapon: "marksman",
  weapons,
  enemies: {
    raptor: {
      label: "Velociraptor",
      maxHealth: 72,
      speed: 3.25,
      damagePerSecond: 4.1,
      radius: 1.35,
      height: 2.25,
      bodyColor: "#8c7059",
      weakColor: "#f6c84a",
      weakPointHeight: 1.58,
      weakPointRadius: 0.5,
      weakPointForwardOffset: 1.05,
      modelFileName: "Velociraptor.glb",
      modelScale: 0.48,
      modelYaw: Math.PI,
      animationName: "run",
      animationSpeed: 0.78,
      bodyStyle: "runner",
      score: 100,
    },
    parasaur: {
      label: "Parasaurolophus",
      maxHealth: 96,
      speed: 2.15,
      damagePerSecond: 4.8,
      radius: 1.45,
      height: 2.35,
      bodyColor: "#4e7f86",
      weakColor: "#f5d36b",
      weakPointHeight: 1.65,
      weakPointRadius: 0.48,
      weakPointForwardOffset: 1.2,
      modelFileName: "Parasaurolophus.glb",
      modelScale: 0.36,
      modelYaw: Math.PI,
      animationName: "run",
      animationSpeed: 0.62,
      bodyStyle: "runner",
      score: 140,
    },
    rex: {
      label: "T-Rex",
      maxHealth: 155,
      speed: 1.45,
      damagePerSecond: 6.4,
      radius: 1.72,
      height: 2.9,
      bodyColor: "#9a6c43",
      weakColor: "#ffb13d",
      weakPointHeight: 2.05,
      weakPointRadius: 0.56,
      weakPointForwardOffset: 1.35,
      modelFileName: "T-Rex.glb",
      modelScale: 0.43,
      modelYaw: Math.PI,
      animationName: "walk",
      animationSpeed: 0.58,
      bodyStyle: "runner",
      score: 220,
    },
    brute: {
      label: "Armored Trike",
      maxHealth: 190,
      speed: 1.08,
      damagePerSecond: 7.3,
      radius: 1.9,
      height: 2.35,
      bodyColor: "#8f806f",
      weakColor: "#ff4d35",
      weakPointHeight: 1.2,
      weakPointRadius: 0.55,
      weakPointForwardOffset: 2.25,
      modelFileName: "Triceratops.glb",
      modelScale: 0.33,
      modelYaw: Math.PI,
      animationName: "walk",
      animationSpeed: 0.48,
      bodyStyle: "heavy",
      score: 250,
    },
    stego: {
      label: "Stegosaurus",
      maxHealth: 165,
      speed: 0.92,
      damagePerSecond: 6.6,
      radius: 1.95,
      height: 2.35,
      bodyColor: "#7b8c45",
      weakColor: "#ff6a42",
      weakPointHeight: 1.35,
      weakPointRadius: 0.55,
      weakPointForwardOffset: 1.85,
      modelFileName: "Stegosaurus.glb",
      modelScale: 0.34,
      modelYaw: Math.PI,
      animationName: "walk",
      animationSpeed: 0.5,
      bodyStyle: "heavy",
      score: 230,
    },
    sauropod: {
      label: "Apatosaurus",
      maxHealth: 260,
      speed: 0.68,
      damagePerSecond: 8.2,
      radius: 2.35,
      height: 3.05,
      bodyColor: "#667c8e",
      weakColor: "#ff3d54",
      weakPointHeight: 2.2,
      weakPointRadius: 0.65,
      weakPointForwardOffset: 2.3,
      modelFileName: "Apatosaurus.glb",
      modelScale: 0.39,
      modelYaw: Math.PI,
      animationName: "walk",
      animationSpeed: 0.42,
      bodyStyle: "heavy",
      score: 340,
    },
  },
  waves: [
    { time: 0.7, kind: "raptor", lane: "center" },
    { time: 10, kind: "parasaur", lane: "left" },
    { time: 15, kind: "raptor", lane: "right" },
    { time: 22, kind: "raptor", lane: "center", count: 2, spacingSeconds: 1.6 },
    { time: 31, kind: "brute", lane: "left" },
    { time: 40, kind: "parasaur", lane: "right", count: 2, spacingSeconds: 1.2 },
    { time: 50, kind: "rex", lane: "left" },
    { time: 57, kind: "stego", lane: "center" },
    { time: 68, kind: "raptor", lane: "left", count: 2, spacingSeconds: 1.4 },
    { time: 72, kind: "raptor", lane: "right", count: 2, spacingSeconds: 1.4 },
    { time: 82, kind: "brute", lane: "right" },
    { time: 88, kind: "raptor", lane: "center", count: 3, spacingSeconds: 1.1 },
    { time: 96, kind: "sauropod", lane: "center" },
    { time: 101, kind: "rex", lane: "right" },
  ],
};

export const aiIterationExamples = [
  {
    feedback: "Make the jungle brighter and easier to read.",
    edit: "Raise visualTheme.lightIntensity, reduce fogDensity, shift skyHorizon warmer.",
  },
  {
    feedback: "The dinosaurs are hard to see.",
    edit: "Increase enemy body contrast and weakColor brightness in tuning.enemies.",
  },
  {
    feedback: "The rifle should feel stronger.",
    edit: "Increase weapon.damage, recoil, tracerIntensity, and hit flash duration.",
  },
  {
    feedback: "This is too hard for a first run.",
    edit: "Lower raptor speed and damagePerSecond, or raise baseIntegrity.",
  },
  {
    feedback: "Make the HUD feel more sci-fi.",
    edit: "Adjust hudPrimary, add scanline opacity, and increase scope overlay contrast.",
  },
];
